<#
.SYNOPSIS
    Starts the demo site: MediaMTX + fake ONVIF cameras, then LarisVMS Web and a recorder node.

.DESCRIPTION
    Every process runs in the background with its output in <dataRoot>\logs\. Their process IDs are
    saved to <dataRoot>\demo-processes.json so stop-demo.ps1 can stop them.

      MediaMTX     rtsp://<camera-ip>:554/<id>_main|_sub, looping the clips from fetch-clips.ps1
      FakeOnvif    http://<camera-ip>/onvif/device_service, plus WS-Discovery on the demo adapter
      Web          https://localhost:8444/  (dotnet run, Release)
      Node         the release build unpacked by fetch-tools.ps1 (includes the Vision Service)

    The node needs -RegistrationKey the first time only, after the setup wizard shows the key.
    Its registration is then kept in %ProgramData%\LarisVMS\node.config.

.EXAMPLE
    .\start-demo.ps1 -CamerasOnly
    .\start-demo.ps1 -NoNode                         # first run: do the setup wizard, then...
    .\start-demo.ps1 -NodeOnly -RegistrationKey abc123
    .\start-demo.ps1                                 # later runs: everything
#>
param(
    [switch]$CamerasOnly,
    [switch]$NoNode,
    [switch]$NodeOnly,
    [string]$RegistrationKey,
    # ffmpeg for the recorder node (and the Vision Service it starts) instead of the one on PATH,
    # for example a wrapper that adds options to its calls. LARISDEMO_REAL_FFMPEG_DIR is set to the
    # PATH ffmpeg's folder so a wrapper can find the real tools.
    [string]$NodeFfmpegPath
)

. "$PSScriptRoot\common.ps1"

New-Item -ItemType Directory -Force $LogsDir | Out-Null
$pidFile = Join-Path $DataRoot 'demo-processes.json'
$running = @{}
if (Test-Path $pidFile) { (Get-Content $pidFile -Raw | ConvertFrom-Json).PSObject.Properties | ForEach-Object { $running[$_.Name] = $_.Value } }

function Start-DemoProcess([string]$Name, [string]$Exe, [string[]]$Arguments, [string]$WorkingDirectory = $DemoRoot) {
    if ($running.ContainsKey($Name) -and (Get-Process -Id $running[$Name] -ErrorAction SilentlyContinue)) {
        Write-Ok "$Name already running (PID $($running[$Name]))"
        return
    }
    $out = Join-Path $LogsDir "$Name.log"
    $err = Join-Path $LogsDir "$Name.err.log"
    $p = Start-Process -FilePath $Exe -ArgumentList $Arguments -WorkingDirectory $WorkingDirectory `
        -RedirectStandardOutput $out -RedirectStandardError $err -WindowStyle Hidden -PassThru
    $running[$Name] = $p.Id
    $running | ConvertTo-Json | Set-Content $pidFile
    Write-Ok "$Name started (PID $($p.Id)), log: $out"
}

function Wait-Port([string]$HostName, [int]$Port, [int]$Seconds = 120) {
    $deadline = (Get-Date).AddSeconds($Seconds)
    while ((Get-Date) -lt $deadline) {
        try { $c = [Net.Sockets.TcpClient]::new(); $c.Connect($HostName, $Port); $c.Dispose(); return $true } catch { Start-Sleep -Seconds 1 }
    }
    return $false
}

$ffmpeg = Get-ToolPath ffmpeg

if (-not $NodeOnly) {
    if (-not (Get-NetAdapter -Name "vEthernet ($($DemoConfig.network.switchName))" -ErrorAction SilentlyContinue)) {
        throw "The demo network isn't set up. Run setup-network.ps1 in an elevated PowerShell first."
    }
    $mediamtx = Join-Path $BinDir 'mediamtx.exe'
    if (-not (Test-Path $mediamtx)) { throw 'MediaMTX is missing. Run fetch-tools.ps1 first.' }

    Write-Step 'RTSP server (MediaMTX)'
    $ffmpegFwd = $ffmpeg -replace '\\', '/'
    $paths = foreach ($cam in $DemoConfig.cameras) {
        foreach ($stream in 'main', 'sub') {
            $clip = (Join-Path $ClipsDir "$($cam.id)_$stream.mp4") -replace '\\', '/'
            if (-not (Test-Path $clip)) { throw "Missing $clip. Run fetch-clips.ps1 first." }
            @"
  $($cam.id)_${stream}:
    runOnInit: '"$ffmpegFwd" -hide_banner -loglevel error -re -stream_loop -1 -i "$clip" -c copy -f rtsp -rtsp_transport tcp rtsp://127.0.0.1:`$RTSP_PORT/`$MTX_PATH'
    runOnInitRestart: yes
"@
        }
    }
    $yml = Join-Path $DataRoot 'mediamtx.yml'
    @"
# Generated by start-demo.ps1. Edit cameras.json instead.
logLevel: info
rtspAddress: :$($DemoConfig.rtspPort)
rtspTransports: [tcp]
rtmp: no
hls: no
webrtc: no
srt: no
api: no
metrics: no
pprof: no
playback: no
paths:
$($paths -join "`n")
"@ | Set-Content $yml -Encoding utf8
    Start-DemoProcess 'mediamtx' $mediamtx @($yml)

    Write-Step 'Fake ONVIF cameras'
    $env:FFMPEG_PATH = $ffmpeg
    Start-DemoProcess 'fakeonvif' 'dotnet' @('run', '--project', "`"$DemoRoot\FakeOnvif`"", '-c', 'Release', '--',
        '--config', "`"$DemoRoot\cameras.json`"")
}

if (-not $CamerasOnly -and -not $NodeOnly) {
    Write-Step 'LarisVMS Web'
    Start-DemoProcess 'web' 'dotnet' @('run', '--project', "`"$RepoRoot\src\LarisVMS.Web`"", '-c', 'Release') $RepoRoot
    Write-Host 'Waiting for https://localhost:8444/ (the first build takes a minute or two)...'
    if (Wait-Port 'localhost' 8444 300) { Write-Ok 'Web is up: https://localhost:8444/' } else { Write-Warning "Web didn't come up; check $LogsDir\web.log" }
}

if (-not $CamerasOnly -and -not $NoNode) {
    Write-Step 'LarisVMS recorder node'
    $nodeExe = Join-Path $DataRoot 'node-msi\PFiles64\LarisVMS\Node\LarisVMS.Node.exe'
    if (-not (Test-Path $nodeExe)) { throw "Missing $nodeExe. Run fetch-tools.ps1 first." }
    $recordings = Join-Path $DataRoot 'recordings'
    New-Item -ItemType Directory -Force $recordings | Out-Null
    $nodeFfmpeg = $ffmpeg
    if ($NodeFfmpegPath) {
        $nodeFfmpeg = (Resolve-Path $NodeFfmpegPath).Path
        $env:LARISDEMO_REAL_FFMPEG_DIR = Split-Path $ffmpeg
    }
    $nodeArgs = @('--server-url', 'https://localhost:8444', '--storage-root', "`"$recordings`"", '--insecure-tls', '--ffmpeg-path', "`"$nodeFfmpeg`"")
    if ($RegistrationKey) { $nodeArgs += @('--registration-key', $RegistrationKey) }
    elseif (-not (Test-Path (Join-Path $env:ProgramData 'LarisVMS\node.config'))) {
        throw 'The node has never registered. Run the setup wizard, then: .\start-demo.ps1 -NodeOnly -RegistrationKey <key>'
    }
    Start-DemoProcess 'node' $nodeExe $nodeArgs (Split-Path $nodeExe)
}

Write-Ok "`nDemo running. Stop it with .\stop-demo.ps1"
